version: "3.7"

services:

  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: serverList-nestjs
    command: npm run start
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    networks:
      - serverListNetwork
    depends_on:
      - redis

  redis:
    container_name: serverList-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - serverListNetwork

networks:
  serverListNetwork:
    driver: bridge